[package]
name = "static-file-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.11"
axum-extra = "0.7.1"
clap = { version = "4.1.8", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
tracing = "0.1"
colored="2.0.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
